CREATE DATABASE IF NOT EXISTS metalloprodukciya_it
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE metalloprodukciya_it;

CREATE TABLE IF NOT EXISTS support_requests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  employee_name VARCHAR(150) NOT NULL,
  department VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL,
  phone VARCHAR(60) NOT NULL,
  topic VARCHAR(120) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
